### ISSUE TITLE
Weird filling behavior for paragraphs containing links

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#173]
This is for version 20160928.932.

To reproduce, create a new buffer in markdown-mode, disable auto-fill-mode, and set fill-column to 79. (The latter two aren't necessary, they just make the reproduction more obvious.) Then, insert the following as a single line:

``` markdown
aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa [aaa aaa aaa aaa](aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) aaa aaa aaa aaa aaa.
```

The "words" themselves don't matter, it's only important that there is a lengthy paragraph with a link with a long URL. Then hit M-q to fill the paragraph. The result is

``` markdown
aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa
aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa
aaa [aaa aaa aaa aaa](aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) aaa aaa aaa aaa
aaa.
```

Note that there's a single "aaa" in front of the link, even though it would have fit on the previous line.

**Comment by jrblevin** [comment]
This seems to have been fixed already. I added your example as a test case to prevent future regressions. Thanks for the report.

**Comment by phst** [comment]
Thanks, but I think this isn't fixed yet if the fill column is set to 79 (this does seem to be necessary after all).

**Comment by phst** [comment]
Another case is e.g.

```markdown
aaa [aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa](a) aaa.
```

with a fill column of 40. Filling that paragraph should introduce line breaks inside the link text, but doesn't.

**Comment by jrblevin** [comment]
Thanks. I missed the point about setting the `fill-column` to 79.

Indeed, `markdown-mode` inhibits line breaks inside links:

``` emacs-lisp
(add-hook 'fill-nobreak-predicate
          'markdown-inside-link-p nil t)
```

I think there is a good reason why, but I'll have to check to refresh my memory.

**Comment by jrblevin** [comment]
Looks like this originated in 0c239e2f2, presumably as an aesthetic preference. I'll work on making this behavior customizable, but as a temporary workaround you can write a function that runs with `markdown-mode-hook` to remove the hook:

```
(remove-hook 'fill-nobreak-predicate 'markdown-inside-link-p t)
```

**Comment by phst** [comment]
I think https://github.com/jrblevin/markdown-mode/commit/0c239e2f20059804cbf44d4d9943d2420cef67ba is for a different case, where filling could really change semantics. The original commit is https://github.com/jrblevin/markdown-mode/commit/66566a550dfdf30f8b8e8522d196dd00cfc9ae88, with the explanation "maruku does not like it when you do that". No idea whether that's still current or whether maruku has been fixed.

**Comment by jrblevin** [comment]
Thanks for finding the original commit. I remember that now (nearly 8 years ago!)

It seems the latest Maruku correctly parses links with line breaks in the text ([see here](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bmulti-line%0Alink%5D(url))), so I will revert the non-breaking behavior.

**Comment by phst** [comment]
I've been using the workaround in https://github.com/jrblevin/markdown-mode/issues/173#issuecomment-312496856 for a couple of days now and haven't encountered any issues.

**Comment by jrblevin** [comment]
Thanks again for the report.

**Comment by phst** [comment]
Thanks for the fix!

**Comment by xenophonf** [comment]
@jrblevin sorry to necro this, but I wanted to put my solution to stopping line wrapping Markdown links here.  Given the following Markdown:

```markdown
This is a [very long link](https://www.example.com/very/very/very/very/long).

This is a [ridiculously long link](https://www.example.com/very/very/very/very/very/very/very/long) with stuff coming after.

- This is a [ridiculously long link in a list](https://www.example.com/very/very/very/very/very/very/very/long) with stuff coming after.
```

And the following code in my .emacs:

```elisp
(defun mxe:markdown-mode-install-fill-nobreak-predicates ()
  "These hooks are mode-specific and must be buffer-local as a                                                                                                                               
result."
  (add-hook 'fill-nobreak-predicate
            'markdown-inside-link-p nil t))

(with-eval-after-load 'markdown-mode
  (add-hook 'markdown-mode-hook #'mxe:markdown-mode-install-fill-nobreak-predicates))
```

The `fill-paragraph` command reformats paragraphs with long links like so:

```markdown
This is
a [very long link](https://www.example.com/very/very/very/very/long).

This is
a
[ridiculously long link](https://www.example.com/very/very/very/very/very/very/very/long) with
stuff coming after.

- This is
  a
  [ridiculously long link in a list](https://www.example.com/very/very/very/very/very/very/very/long) with
  stuff coming after.
```

I'd prefer space within links be treated as non-breakable while allowing breaks before and after:

```elisp
(defun mxe:markdown-link-fill-nobreak ()
  "Do not break lines in the middle of Markdown links when filling                                                                                                                           
paragraphs.  This function is designed for use in                                                                                                                                            
`fill-nobreak-predicate'.                                                                                                                                                                    
                                                                                                                                                                                             
    [A Markdown link](https://www.example.com/)                                                                                                                                              
    ^                                         ^                                                                                                                                              
    |--- breaks allowed before, after here ---|"
  ;; TODO: memoize this somehow                                                                                                                                                              
  (let ((pos (point)))
    (cl-destructuring-bind (start end text link ref title bang)
        (markdown-link-at-pos pos)
      (< start pos end))))

(defun mxe:markdown-mode-install-fill-nobreak-predicates ()
  "These hooks are mode-specific and must be buffer-local as a                                                                                                                               
result."
  (add-hook 'fill-nobreak-predicate
            #'mxe:markdown-link-fill-nobreak nil t))

(with-eval-after-load 'markdown-mode
  (add-hook 'markdown-mode-hook #'mxe:markdown-mode-install-fill-nobreak-predicates))
```

Now long links get placed on their own line.  Filled paragraphs look neater as a result.

```markdown
This is a
[very long link](https://www.example.com/very/very/very/very/long).

This is a
[ridiculously long link](https://www.example.com/very/very/very/very/very/very/very/long)
with stuff coming after.
  
- This is a
  [ridiculously long link in a list](https://www.example.com/very/very/very/very/very/very/very/long)
  with stuff coming after.
```

**Comment by whame** [comment]
As a slight performance improvement of @xenophonf's excellent solution, I stripped `markdown-link-at-pos` to only calculate and return `start` and `end`, and used that modified version in `markdown-link-fill-nobreak`. Benchmark (with `benchmark`) shows around 10 times speed-up :)
